####################################
# This file was generated by hookup
# @author Gavin Staniforth
# http://github.com/gsdevme/hookup
#
# If you wish to make manual changes
# make them to ~/.ssh/config.orig
#####################################


<?php /** @var \Hookup\Model\Server $server */ ?>
<?php if (isset($servers)) foreach($servers as $server): ?>
<?=$this->write('Host %s', $server->getHost())?>
    <?=$this->write('Hostname %s', $server->getHostname())?>
    <?=$this->write('User %s', $server->getUser())?>
    <?=$this->write('IdentityFile %s', $server->getIdentityFile())?>
    <?=$this->write('LocalForward %s', $server->getLocalForward())?>
    <?=$this->write('ProxyCommand %s', $server->getProxyCommand())?>
    <?=$this->write('Port %s', $server->getPort())?>
<?php endforeach; ?>
